services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8000
    container_name: nextjs-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  redis:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"
